<?php

return [
    'advancedBan' => ['nullable', 'array'],
    'articles' => ['nullable', 'array'],
    'changelog' => ['nullable', 'array'],
    'cps' => ['nullable', 'array'],
    'discord' => ['nullable', 'array'],
    'faq' => ['nullable', 'array'],
    'footer' => ['nullable', 'array'],
    'forum' => ['nullable', 'array'],
    'header' => ['nullable', 'array'],
    'home' => ['nullable', 'array'],
    'pages' => ['nullable', 'array'],
    'login' => ['nullable', 'array'],
    'liteBans' => ['nullable', 'array'],
    'passwordReset' => ['nullable', 'array'],
    'profile' => ['nullable', 'array'],
    'project' => ['nullable', 'array'],
    'register' => ['nullable', 'array'],
    'shop' => ['nullable', 'array'],
    'staff' => ['nullable', 'array'],
    'skinApi' => ['nullable', 'array'],
    'support' => ['nullable', 'array'],
    'sliders' => ['nullable', 'array'],
    'vote' => ['nullable', 'array'],
    'wiki' => ['nullable', 'array'],
];
